INDUSTRIES = [
("ACCEPTING HOUSES",3,"Medium"),("ACCOUNTING",3,"Medium"),("AIR TRANSPORT",1,"Low"),("AMUSEMENT & CATERING",1,"Low"),("AUDITING",3,"Medium"),("BEER, WINE & SPIRITS",1,"Low"),("BETTING AND GAMBLING",4,"High"),("BEVERAGES",1,"Low"),("BROADCASTING",1,"Low"),("BUILDING CONTRACTORS",1,"Low"),("BUILDING SOCIETIES",4,"High"),("CHROME",4,"High"),("CIVIL ENGINEERING CONTRACTORS",1,"Low"),("CLOTHING/FOOTWEAR",1,"Low"),("COMMERCIAL BANKS",3,"Medium"),("DAIRY",1,"Low"),("DEPARTMENTAL STORES",1,"Low"),("DISCOUNT HOUSES",3,"Medium"),("EDUCATION",1,"Low"),("ENERGY",2,"Low"),("ENTERTAINMENT",2,"Low"),("FARMING",1,"Low"),("FERTILISERS INSECTICIDES PESTICIDES",3,"Medium"),("FINANCE",3,"Medium"),("FINANCIAL TECHNOLOGY",4,"High"),("FISHING",2,"Low"),("FORESTRY AND WILDLIFE",1,"Low"),("GOVERNMENT",3,"Medium"),("HORTICULTURE",1,"Low"),("HOSPITALITY",2,"Low"),("INDUSTRIAL AND HEAVY EQUIPMENT",2,"Low"),("INSURANCE COMPANIES",3,"Medium"),("INFORMATION TECHNOLOGY",2,"Low"),("LEGAL",4,"High"),("LIVESTOCK",1,"Low"),("LOCAL AUTHORITIES (INC MUNICIPAL)",4,"High"),("LOGISTICS AND TRANSPORTATION",3,"Medium"),("MANUFACTURING",4,"High"),("MEDICAL PROFESSIONS AND HEALTHCARE",2,"Low"),("MINING (OTHER)",4,"High"),("MINING HOUSES",4,"High"),("MINING PRECIOUS METALS",4,"High"),("MOTOR TRADE (CAR DEALERS)",3,"Medium"),("NON-PROFIT AND CHARITABLE",4,"High"),("PENSION & PROVIDENT FUNDS",3,"Medium"),("POULTRY",1,"Low"),("PRECIOUS STONES AND METALS",4,"High"),("PRINTING AND PUBLISHING",1,"Low"),("PROFESSIONAL SERVICES",3,"Medium"),("REAL ESTATE",4,"High"),("RETAILERS",1,"Low"),("ROAD HAULAGE",1,"Low"),("SALES AND MARKETING",2,"Low"),("SECURITY BROKERS & DEALERS",3,"Medium"),("SOAPS TOILETRIES & PHARMACEUTICALS",2,"Low"),("SPORTING",3,"Medium"),("TELECOMMUNICATIONS",1,"Low"),("TOBACCO",3,"Medium"),("TOURISM",4,"High"),("TRUST COMPANIES & EXECUTORS",4,"High"),("UNKNOWN",5,"Auto High"),("WHOLESALERS",3,"Medium"),
]
CUSTOMER_TYPES = [
("ASSOCIATION/SOCIETY",2,"Low"),("CLOSE CORPORATE",1,"Low"),("CLUBS",2,"Low"),("Cooperative Company",3,"Medium"),("CO-OPERATIVES",3,"Medium"),("CORRESPONDENT BANK",4,"High"),("EMBASSY & CONSULATE",4,"High"),("Estate",3,"Medium"),("ESTATE AC",2,"Low"),("Foreign Company",3,"Medium"),("FOREIGN NATIONALS",3,"Medium"),("Government (Agency)",1,"Low"),("Government (Consulate)",1,"Low"),("Government (Multinational/Regional Development Bank)",1,"Low"),("Government (Municipality)",1,"Low"),("Government (State-Owned Body)",1,"Low"),("INDIVIDUAL PERSON",1,"Low"),("LISTED/Public Limited Company (Recognised Stock Exchange)",1,"Low"),("MINOR CHILD",1,"Low"),("NON-LISTED COMPANY CLIENT",2,"Low"),("NON-PROFIT CO (NPC)",4,"High"),("OTHER LEGAL ENTITY",2,"Low"),("Partnership, Syndicate, Joint Ventures or Association",2,"Low"),("PARTNERSHIPS",2,"Low"),("Private Investment Company (PIC)",5,"High"),("Pvt Business Corporation/Sole Proprietary",2,"Low"),("Pvt Limited Company",2,"Low"),("RELIGIOUS BODY",3,"Medium"),("SPV, SPE, Special Investment Vehicle",5,"High"),("STATE OWNED ENTERPRISE",4,"High"),("TRUST INTER VIVOS",4,"High"),("TRUSTS",4,"High"),("UNKNOWN COMPANY TYPE",5,"High"),
]
PEP_SANCTIONS_STATUSES = [("Screened, PEP not identified, not on Sanctions lists",1,"Minimal Risk"),("Screened, PEP identified, not on Sanctions lists",3,"Medium"),("Screened, PEP not identified, on Sanctions lists",5,"Auto High"),("Screened, PEP identified, on Sanctions lists",5,"Auto High"),("Not Screened",5,"High")]
# Full occupation seed from the supplied workbook should be extended here as needed; these core entries are used by the portal and risk engine.
OCCUPATIONS = [("ACCOUNTANT",2,"Low"),("ADMINISTRATOR",1,"Low"),("ADVOCATE",3,"Medium"),("AIRLINE CABIN STAFF",4,"High"),("ATTORNEY",4,"High"),("AUDITOR",3,"Medium"),("BANKER",2,"Low"),("BOOKMAKER",4,"High"),("BROKER",3,"Medium"),("CASINO DEALER",4,"High"),("CASHIER",2,"Low"),("CUSTOMS OFFICER",5,"High"),("DEFENSE FORCE",5,"High"),("DIRECTOR",3,"Medium"),("DOCTOR",1,"Low"),("ESTATE AGENT",4,"High"),("FARMER",2,"Low"),("JUDGE",5,"High"),("LAWYER",4,"High"),("MAGISTRATE",5,"High"),("MEMBER OF PARLIAMENT",5,"High"),("NURSE",1,"Low"),("POLICE",3,"Medium"),("PROFESSIONAL",3,"Medium"),("SELF EMPLOYED",3,"Medium"),("STOCKBROKER",4,"High"),("STUDENT",1,"Low"),("TEACHER",1,"Low"),("UNEMPLOYED",2,"Low"),("UNKNOWN",5,"High")]
COUNTRY_RISK = {"Afghanistan":(5,"High"),"Albania":(5,"High"),"Algeria":(5,"High"),"American Samoa":(1,"Low"),"Andorra":(5,"High"),"Angola":(5,"High"),"Anguilla":(3,"Medium"),"Argentina":(3,"Medium"),"Australia":(1,"Low"),"Austria":(1,"Low"),"Bahamas":(5,"High"),"Botswana":(1,"Low"),"Canada":(1,"Low"),"China":(3,"Medium"),"France":(1,"Low"),"Germany":(1,"Low"),"India":(5,"High"),"Iran":(5,"Auto High"),"Korea (North)":(5,"Auto High"),"Myanmar":(5,"Auto High"),"South Africa":(5,"High"),"United Arab Emirates":(5,"High"),"United Kingdom":(1,"Low"),"United States":(1,"Low"),"Zambia":(1,"Low"),"Zimbabwe":(1,"Low")}
